name: keptn-workflow
on:
  workflow_dispatch:
jobs:
  keptn_configure:
    runs-on: "ubuntu-latest"
    steps:
      - name: Installing keptn-cli
        run: |
          curl -sL https://get.keptn.sh/ | bash
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: kubectl
          service_account_key: ${{ secrets.GL_SA }}
      - name: connecting to GKE
        run: |
          gcloud container clusters get-credentials keptnv1 --zone us-central1-b --project project-net-408408
          kubectl get nodes
          kubectl get ns
          
