name: keptn-workflow
on:
  workflow_dispatch:
jobs:
  keptn_configure:
    runs-on: "ubuntu-latest"
    steps:
      - name: Installing keptn-cli
        run: |
          curl -sL https://get.keptn.sh/ | bash
          keptn version
